on: [push]
jobs:
        deploy_arhyth:
                if: contains(github.event.commits[0].message, '[blog]')
                runs-on: ubuntu-latest
                name: deploy SSG blog
                steps:
                        - uses: actions/checkout@v2
                        - uses: actions/checkout@v2
                          with:
                                  repository: arhyth/arhyth.github.io
                                  path: built
                                  persist-credentials: false
                                  fetch-depth: 0
                        - name: build pages
                          uses: ./
                        - name: commit built
                          run: |
                                  cd built
                                  git config --local user.email "arhyth@gmail.com"
                                  git config --local user.name "David Ebreo"
                                  COMMIT_MESSAGE="${{ github.event.commits[0].message }}"
                                  COMMIT_MESSAGE="$(echo $COMMIT_MESSAGE | sed 's|\[blog\]\s*||')"
                                  git add .
                                  git commit -m "$COMMIT_MESSAGE"
                        - name: push built
                          uses: ad-m/github-push-action@master
                          with:
                                  repository: arhyth/arhyth.github.io
                                  github_token: ${{ secrets.BLOG_TOKEN }}
                                  directory: built
